const langArr = {
  "hero__title": {
    "cs": "100% BONUS NA PRVNÍ VKLAD DO 2460 CZK",
    "da": "100 % FØRSTE INDBETALINGSBONUS PÅ OP TIL 750 DKK",
    "en": "100% BONUS ON THE FIRST DEPOSIT UP TO 100 EUR",
    "de": "100 % BONUS FÜR DIE ERSTE EINZAHLUNG VON BIS ZU 100 EUR",
    "it": "BONUS DEL 100% SUL PRIMO DEPOSITO FINO A 100 EUR",
    "no": "100% BONUS PÅ FØRSTE INNSKUDD OPPTIL 1000 NOK",
    "pl": "BONUS 100% ZA PIERWSZY DEPOZYT DO 100 EUR",
    "sv": "100% FÖRSTA INSÄTTNINGSBONUS UPP TILL 1100 SEK",
  },
  "btn": {
    "cs": "ZÍSKEJTE BONUS",
    "da": "FÅ BONUSEN",
    "en": "GET THE BONUS",
    "de": "HOL DIR DEN BONUS",
    "it": "OTTIENI IL BONUS",
    "no": "FÅ BONUSEN",
    "pl": "ODBIERZ BONUS",
    "sv": "FÅ BONUSEN",
  },
  "bonus__title": {
    "cs": "Jak získat bonus",
    "da": "Sådan får du din bonus",
    "en": "How to get your bonus",
    "de": "Wie bekommt man den Bonus",
    "it": "Come ricevere il bonus",
    "no": "Hvordan kan jeg motta en bonus",
    "pl": "Jak otrzymać bonus",
    "sv": "Hur får jag bonusen",
  },
  "bonus-guide-1": {
    "cs": "Zaregistrujte se na webu Megapari",
    "da": "Registrer på  Megapari hjemmesiden",
    "en": "Register on the Megapari site",
    "de": "Registrieren Sie sich auf der Megapari-Webseite",
    "it": "Registrati sul  sito web di Megapari",
    "no": "Registrer på  Megapari-nettsiden",
    "pl": "Zarejestruj się  na stronie Megapari",
    "sv": "Registrera dig på Megaparis hemsida",
  },
  "bonus-guide-2": {
    "cs": "Vyplňte všechna pole s osobními údaji v sekci Můj účet",
    "da": "Udfyld alle felterne med personlige oplysninger under Min konto",
    "en": "Fill in all the personal information fields in My Account",
    "de": "Füllen Sie alle Felder für Ihre persönlichen Informationen unter Mein Konto aus",
    "it": "Compila tutti i campi relativi ai dati personali nella sezione Il mio conto",
    "no": "Fyll inn alle feltene for personlige opplysninger i Min Konto",
    "pl": "Wypełnij wszystkie pola w dziale „Moje konto”",
    "sv": "Fyll i alla personuppgifter",
  },
  "bonus-guide-3": {
    "cs": "Dobijte si svůj účet do 2460 CZK",
    "da": "Foretag en indbetaling på op til 750 DKK",
    "en": "Make a deposit of up to 100 EUR (or equivalent in another currency)",
    "de": "Zahlen Sie bis zu 100 EUR ein",
    "it": "Effettua un deposito fino a 100 EUR",
    "no": "Gjør et innskudd på opptil 1000 NOK",
    "pl": "Doładuj konto kwotą do 100 EUR",
    "sv": "Gör en insättning på upp till 1100 SEK",
  },
  "bonus-guide-4": {
    "cs": "Bonus se automaticky připisuje na účet uživatele po provedení vkladu (bonusová částka však nemůže přesahovat 2460 CZK)",
    "da": "Bonussen krediteres automatisk til en kundes konto efter en indbetaling er foretaget (bonusbeløbet kan ikke overstige 750 DKK)",
    "en": "The bonus is automatically credited to a customer's account after a deposit has been made (the bonus amount cannot exceed 100 EUR)",
    "de": "Der Bonus wird nach einer Einzahlung automatisch dem Konto des Kunden gutgeschrieben (der Bonusbetrag kann 100 EUR nicht überschreiten)",
    "it": "Il bonus viene accreditato automaticamente sul conto del cliente dopo che è stato effettuato un deposito (l'importo del bonus non può superare 100 EUR)",
    "no": "Bonusen krediteres automatisk til kundens konto etter at et innskudd er utført (bonusbeløpet kan ikke overstige 1000 NOK)",
    "pl": "Bonus zostanie doliczony do stanu konta automatycznie po złożeniu depozytu (kwota bonusu nie może przekroczyć 100 EUR)",
    "sv": "Bonusen kommer automatiskt sättas in på ett kundkonto efter att insättningen har genomförts (bonusbeloppet får inte överstiga 1100 SEK)",
  },
  "bonus__link": {
    "cs": "Veškeré podmínky jak získat bonus naleznete zde.",
    "da": "Få den fulde information om bonusbetingelser her.",
    "en": "All the conditions of the bonus are available here",
    "de": "Alles Bonusbedingungen finden Sie hier",
    "it": "Tutte le condizioni del bonus sono disponibili qui",
    "no": "Du kan bli kjent med alle bonusvilkår her",
    "pl": "Z warunkami bonusu można zapoznać się tutaj",
    "sv": "De fullständiga villkoren för bonusen finns här.",
  },
}


